name: Build and test

on: [push]

jobs:
  build:

    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.08.x
          - 4.09.x
          - 4.10.x
          - 4.11.x
          - 4.12.x
          - 4.13.x

    steps:
      - uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Check formatting
        run: opam exec -- dune build @fmt

      - name: Run unit tests
        run: opam exec --  dune build @test/runtest

      - name: Run integration tests
        run: opam exec --  dune build @test/runtest-slow
        if: ${{ matrix.ocaml-compiler == '4.12.x' }}
        env:
          toggl_token: ${{ secrets.TOGGL_TOKEN }}
